# Generated by Django 2.1.7 on 2019-04-03 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20190326_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='pwd',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
